version: '3.4'

services:
  web:
    build: ./web/
    command: gunicorn --bind 0.0.0.0:5000 main:app
    restart: always
    environment:
      FLASK_APP: app
      FLASK_CONFIG: config.ProductionConfig
      DATABASE_URL: postgresql://db_admin:v3rY_h4Rd_t0_gu355_p455w0Rd@db:5432/digital_library
    ports:
      - "5000:5000"
    networks:
      - db_nw
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: digital_library
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: v3rY_h4Rd_t0_gu355_p455w0Rd
    ports:
        - "5432:5432"
    networks:
      - db_nw

networks:
  db_nw:
    driver: bridge
volumes:
  postgres_data: